dist: xenial
language: php
php:
  - '5.6'
  - '7.2'
  - '7.3'
cache:
  directories:
    - $HOME/.composer/cache
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE qdm160638220_db;'
script:
  - phpunit tests/OutputTest
notifications:
  email: false
